# permissions for end users to view githubactionrunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubactionrunner-viewer-role
rules:
- apiGroups:
  - garo.tietoevry.com
  resources:
  - githubactionrunners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - garo.tietoevry.com
  resources:
  - githubactionrunners/status
  verbs:
  - get
